force-app/main/default/objects/Case/fields/Create_on_Zendesk__c.field-meta.xml
<CustomField>
    <fullName>Create_on_Zendesk__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, then this case will be created on zendeskCRM as well</description>
    <inlineHelpText>If this is checked, then this case will be created on zendeskCRM as well</inlineHelpText>
    <label>Create on Zendesk?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Zendesk_Id__c.field-meta.xml
<CustomField>
    <fullName>Zendesk_Id__c</fullName>
    <description>Once the case is created in Zendesk, the corresponding Zendesk case ID is stored in SF.</description>
    <externalId>true</externalId>
    <inlineHelpText>Once the case is created in Zendesk, the corresponding Zendesk case ID is stored in SF.</inlineHelpText>
    <label>Zendesk Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Zendesk_Integration__mdt/Zendesk_Integration__mdt.object-meta.xml
<CustomObject>
    <label>Zendesk Integration</label>
    <pluralLabel>Zendesk Integration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Zendesk_Integration__mdt/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <label>API Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zendesk_Integration__mdt/fields/Method_Type__c.field-meta.xml
<CustomField>
    <fullName>Method_Type__c</fullName>
    <label>Method Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_ZendeskIntegration.cls
public with sharing class Batch_ZendeskIntegration implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable
{
    public Database.QueryLocator start (Database.BatchableContext bc)
    {
        String caseQuery = 'SELECT Id, Subject, Priority, Description, Zendesk_Id__c FROM Case WHERE Create_on_Zendesk__c = TRUE AND Zendesk_Id__c = null';

        return Database.getQueryLocator(caseQuery);
    }

    public void execute(Database.BatchableContext bc, List<Case> scope)
    {
        if(schema.SObjectType.Case.isUpdateable() && schema.SObjectType.Case.fields.Zendesk_Id__c.isUpdateable())
        {
            List<Case> casesToUpdate = new List<Case>();
            for(Case c : scope)
            {
                String zendeskCaseID = createOnZendesk(c);
                casesToUpdate.add( new Case(Id = c.id, Zendesk_Id__c = zendeskCaseID) );
            }
            if(casesToUpdate.size() > 0)
            {
                SObjectAccessDecision decision = Security.stripInaccessible(AccessType.Updatable, casesToUpdate);
                Database.update( decision.getRecords(), false);
            }
        }
    }

    public void execute(SchedulableContext sc) 
    {
        Database.executeBatch( new Batch_ZendeskIntegration(), 10);
    }

    public void finish(Database.BatchableContext bc)
    {
        
    }

    public static String createOnZendesk(Case c)
    {
        Zendesk_Integration__mdt calloutDetails = Zendesk_Integration__mdt.getInstance('TicketCreateRequest');
        
        if(calloutDetails == null)
        {
            return null;
        }

        HttpRequest req = new HttpRequest();
        req.setEndpoint(calloutDetails.Endpoint_URL__c);
        req.setMethod(calloutDetails.Method_Type__c);
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept', 'application/json');

        String emailAdd                 = calloutDetails.Email__c;
        String apiToken                 = calloutDetails.API_Token__c;
        String authDetailsToBeEncoded   = emailAdd + '/token:' + apiToken;

        String base64EncodedAuthDetails = EncodingUtil.base64Encode( Blob.valueOf(authDetailsToBeEncoded) );
        req.setHeader('Authorization', 'Basic ' + base64EncodedAuthDetails);

        String payload=		'{'+
		'    "ticket": {'+
		'        "comment": {'+
		'            "body": "' + c.Description + '"'+
		'        },'+
		'        "priority": "' + c.Priority.toLowerCase() +'",'+
		'        "subject": "'+ c.Subject +'"'+
		'    }'+
		'}';

        req.setBody(payload);

        Http h = new Http();
        HttpResponse res;

        try
        {
            res = h.send(req);    
        }
        catch(CalloutException e)
        {

            System.debug('CalloutException while callout '+ e.getMessage());
            return null;
        } 
        catch (Exception e) {
            System.debug('Exception while callout '+ e.getMessage());
            return null;   
        }

        System.debug('Response body is='+res.getBody());
        System.debug('Status code is='+res.getStatusCode());

        if( res.getStatusCode() == 201 || res.getStatusCode() == 200) 
        {
            System.debug('callout was successfull');

            String zendeskCaseID;
            Map<String, Object> mappedResponse = (Map<String, Object>)JSON.deserializeUntyped( res.getBody());
            //System.debug('sm resp id='+mappedResponse.get('id'));
            
            if( mappedResponse.get('ticket') != null)
            {
                Map<String, Object> ticketDetailsMap = (Map<String, Object>)mappedResponse.get('ticket');
                return String.valueOf( ticketDetailsMap.get('id') );
            }
            return null;
        }
        else {
            System.debug('callout got failed');
            return null;
        }
    }
}