force-app/main/default/objects/Order_Placed_Platform_Event__e/Order_Placed_Platform_Event__e.object-meta.xml
<CustomObject>
    <label>Order Placed Platform Event</label>
    <pluralLabel>Order Placed Platform Event</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Placed_Platform_Event__e/fields/Table_Number__c.field-meta.xml
<CustomField>
    <fullName>Table_Number__c</fullName>
    <label>Table Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlatformEventSuccessFailureCallback.cls
public with sharing class PlatformEventSuccessFailureCallback implements EventBus.EventPublishSuccessCallback, EventBus.EventPublishFailureCallback
{
    /*

    Order_Placed_Platform_Event__e pe = (Order_Placed_Platform_Event__e)Order_Placed_Platform_Event__e.SObjectType.newSObject(null, true);
    pe.Table_Number__c = '19';
    system.debug('Event UUID is ='+pe.EventUuid);
    Database.SaveResult result = EventBus.publish(pe, new PlatformEventSuccessFailureCallback());

    if(result.isSuccess())
    {
        system.debug('Event with UUID'+pe.EventUuid +' got successfully published!');
    }
    else
    {
        for(Database.Error err : result.getErrors())
        {
            System.debug('Event with UUID'+pe.EventUuid +' got failed to publish with error message:'+err.getMessage());
        }
    }
    */
   
   
   public void onSuccess(EventBus.SuccessResult result)
   {
       System.debug('Success');
       System.debug(result.getEventUuids());
   }

   public void onFailure(EventBus.FailureResult result)
   {
       System.debug('Failure');
       System.debug(result.getEventUuids());
   }

   @AuraEnabled
   public static void createPlatformEventRec()
   {
    try 
    {
        Order_Placed_Platform_Event__e pe = (Order_Placed_Platform_Event__e)Order_Placed_Platform_Event__e.SObjectType.newSObject(null, true);
        pe.Table_Number__c = UUID.randomUUID().toString();
        system.debug('Event UUID is ='+pe.EventUuid);
        Database.SaveResult result = EventBus.publish(pe, new PlatformEventSuccessFailureCallback());

        if(result.isSuccess())
        {
            system.debug('Event with UUID'+pe.EventUuid +' got successfully published!');
        }
        else
        {
            for(Database.Error err : result.getErrors())
            {
                System.debug('Event with UUID'+pe.EventUuid +' got failed to publish with error message:'+err.getMessage());
            }
        }    
    }
    catch (Exception e) 
    {
        throw new AuraHandledException(e.getMessage());
    }
   }
}